//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        public int Id { get; set; }
        public string IdentifyNum { get; set; }
        public System.DateTime Violatedate { get; set; }
        public System.Guid ViolateType { get; set; }
        public string ReasonDetail { get; set; }
        public bool IsBlackList { get; set; }
        public Nullable<int> AttachId { get; set; }
        public System.Guid ApprovalKind { get; set; }
        public string ApprovalLine { get; set; }
        public string ApprovalLineJson { get; set; }
        public System.Guid ApprovalStatus { get; set; }
        public string NextApprover { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
    }
}
