//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorApplicationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitorApplicationDetail()
        {
            this.VisitorCheckDaily = new HashSet<VisitorCheckDaily>();
        }
    
        public int Id { get; set; }
        public int ApplicationMaster { get; set; }
        public string Image { get; set; }
        public string FullName { get; set; }
        public string IdentityCard { get; set; }
        public string TemporaryCard { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string DriverPlate { get; set; }
        public Nullable<System.Guid> VehicleType { get; set; }
        public bool IsContactPerson { get; set; }
        public Nullable<bool> IsWorkHourOfficial { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
    
        public virtual VisitorApplicationMaster VisitorApplicationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorCheckDaily> VisitorCheckDaily { get; set; }
    }
}
