//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Material.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorApplicationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitorApplicationMaster()
        {
            this.VisitorCheckDaily = new HashSet<VisitorCheckDaily>();
            this.VisitorApplicationDetail = new HashSet<VisitorApplicationDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int ApplicationType { get; set; }
        public int DeptId { get; set; }
        public string Applicant { get; set; }
        public string PhoneNumber { get; set; }
        public string HandPhoneNumber { get; set; }
        public int Vendor { get; set; }
        public System.Guid Purpose { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.Guid Gate { get; set; }
        public string Location { get; set; }
        public string LocationOther { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> ApprovalKind { get; set; }
        public string ApprovalLine { get; set; }
        public string ApprovalLineJson { get; set; }
        public Nullable<System.Guid> ApprovalStatus { get; set; }
        public string NextApprover { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
        public bool Temp { get; set; }
    
        public virtual Vendor Vendor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorCheckDaily> VisitorCheckDaily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorApplicationDetail> VisitorApplicationDetail { get; set; }
    }
}
